dist: trusty
sudo: required
cache: bundler

services:
  - mongodb
  - redis-server

addons:
  code_climate:
    repo_token:
      secure: NVRBL7LTRjZFuFM7fb2I6visCA7vIgXm/TFMwC/j1ZdGqv1z+piD1qU1BRsN9EkTdY4Hp+Op8k76u2krFiMSAv145RwRmoDBI69Jl5kXcdeipIzBKP+Wi2kwr+5YN2gbKj8F19NQFGoIyRBy2ZQh9EhIBj2f9a+n+FC519Yw1tqQM8h19opDrXvaE/S9jO7z3za+q7AJijtaodoIuMBoQ84yDXqdva5iE8eB3p90ZebMFYIp9xvwMUjTM3tGVZKqSI0MJITia1NTzfj0h6Xm+mnuFN0NIUcnaZVj/m7VbBJ1stJjgYQT1Xy0B8eUhRpMzrqXwcNCT3N+MnXX7CBkpAd2vlMhg/inR10jt/+TQiScBsMjXsrCeG/3UltN1gdlDQAbb5QhHfwjs6JauWCnIL34oIzpQPYx4MsbulVjwTM9jJfrR4zbSDwb3KCm4KorRPZ9B/sCxGjEnBv0zKGJGrL6JY4L6wYG6Yb3XWdRXqlFY7z9vNoMwuhsnV8MvM+O2xd3Iy8FgR3da/pgWU3h5adYJtbkxBqsB2Y8oGDZ4URPhCFy4G2MXhr9JtUq1ay7JTuHREz+WnmHDTMfUOFrxsZ3TOyi8A+gdXhEUOzK0XVQXSCQVp95mxwc1naU0KsHuyEIx4Gx/VO6RrfFEr+TffPAdUH6pk4lTF+bVf3WVtw=

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  # Nokogiri local binds
  - gem install nokogiri -- --with-cflags='--std=gnu99'
  # FFMPEG
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq ffmpeg

install:
  - make

script:
  - make test

after_success:
  - make report_coverage

notifications:
  slack:
    secure: HvW6jvidsz9p2bQ/xlpCJzYrMLTvEz5ZyutonRmUSK911M7QRiEWY1fLhqpUSky87Kl/bN3MwggSBQ4TsfC3d9o/1odqgKG2dTvPrCqeK4w1DFRXQtKiycq+DebVoEjT+DTM50PC/nMZAIf1avoDar3Bb+7ro/venddquFaS2PmEjH+O6gqxGBPzDM5HG9JrFRkcLpBy0aA1XbQ0RShO1qxC+p8aNObskcIuD+IhqUmDgAczV7kuU1W2oUDf3gxx2WhPSnGclMQ/bQv5c+KB0NRhpHghIJ/Dt3/xNeJp7Sn6FONhQsBOZZxS6csEK2eIpbbs5MW3HE9A9M+lgCEemkR3FFnnOYYAaIV++5nVcRGBBUg1nK9/C/VX4D2CddQxEc5H3P3TBIIVfojPSqyXcBnVhKPhXxDOyaYyTCjAdqGuNdXsByw+4XiDyvRAHdxJ3UFXE2gzInYhGxwPq8NzUcYSKJ931pluJQ0AHN2B8Je9SUWS/hOi4Jc/RhjmV95SdQQpH5aVpkJTgc+NIw/AFm6OyAp4B1FUqA+XeSl3EMR51z3807sBMyw1mVyzv7iYwSfkRVsCvrzsbu6eNAVvDx15oK5hXHDcBG7B1nBJtx7sWFoxRARfrRxjqNYbfMkvJ8nJAIk96xhyLirS1eAUmRrApxk1lLqHrsbniX5UWKE=

deploy:
  provider: heroku
  app:
    master: feedcast-beta
  api_key:
    secure: NUZISzxzlC9yKcygMIXSeSU9ybTYCGzcXGQCj9RQ9M6NkZ1s4UjEjr+WFsfIysALg99FYd8GqiapVrZkJVLWkTCWV1Rkdt3T4pu2O/BRKZzKgy028Zd+DOfeAbj0KpUG4cazqO3wXRBumbM3iQ4m9MVJh5Vhhq7BgKuqtYXs13MoZaLOYWaA+G1AadFNlc+kDKYbFWBcCWSRdc4q6pr2TssJ0UJ5PZDSLkrbu3KX/Vbr2paWTRVpRrMtgcc21kU1D7WPkVumVKmOvPVlscZEqyX5XngP1NWwh7FNTr3E7RDrj3G55etKfPtdjptSlZni3wqMYMhUe1QPYgcBYOxsZLxZQwvUfyarKeBtTmv8NLG5ZNmmnLMXtRQ6N06OQ/VhboxQvg8uPsDdVK0/LUlU28gCsGK0s6bWBjRKhYM5Q+YB8y+BajQjNZEf8knIiyJjEzOofPfDLawlYwURdn18a4ECkOQ9bOfIC7u6ciooN25stOfbja8VCZNKombfv0Yj8/OygN6Wvy2nbcGgibXuzsncgeesidwtsJH+8aJb+ludijoB2NoYs0OF/plBV+aAGU0UPCPr/Tg2cg3ZHrvPBK9lGJWst+2AUe5mZljgZVxGzS73eA9HKK8Sj1gyGB3bdErrqfRBmFs5T1/D7UgCJoxvOvGwcDhNfW6CMHcemfQ=
