services:
  - mongodb

cache: bundler

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - gem install nokogiri -- --with-cflags='--std=gnu99'

install:
  - make

script:
  - make test

addons:
  code_climate:
    repo_token:
      secure: "NVRBL7LTRjZFuFM7fb2I6visCA7vIgXm/TFMwC/j1ZdGqv1z+piD1qU1BRsN9EkTdY4Hp+Op8k76u2krFiMSAv145RwRmoDBI69Jl5kXcdeipIzBKP+Wi2kwr+5YN2gbKj8F19NQFGoIyRBy2ZQh9EhIBj2f9a+n+FC519Yw1tqQM8h19opDrXvaE/S9jO7z3za+q7AJijtaodoIuMBoQ84yDXqdva5iE8eB3p90ZebMFYIp9xvwMUjTM3tGVZKqSI0MJITia1NTzfj0h6Xm+mnuFN0NIUcnaZVj/m7VbBJ1stJjgYQT1Xy0B8eUhRpMzrqXwcNCT3N+MnXX7CBkpAd2vlMhg/inR10jt/+TQiScBsMjXsrCeG/3UltN1gdlDQAbb5QhHfwjs6JauWCnIL34oIzpQPYx4MsbulVjwTM9jJfrR4zbSDwb3KCm4KorRPZ9B/sCxGjEnBv0zKGJGrL6JY4L6wYG6Yb3XWdRXqlFY7z9vNoMwuhsnV8MvM+O2xd3Iy8FgR3da/pgWU3h5adYJtbkxBqsB2Y8oGDZ4URPhCFy4G2MXhr9JtUq1ay7JTuHREz+WnmHDTMfUOFrxsZ3TOyi8A+gdXhEUOzK0XVQXSCQVp95mxwc1naU0KsHuyEIx4Gx/VO6RrfFEr+TffPAdUH6pk4lTF+bVf3WVtw="

after_success:
  - make report_coverage
