development:
  REDIS_URL: redis://127.0.0.1:6379
  FEEDCAST_HTTP_AUTH_USER: admin
  FEEDCAST_HTTP_AUTH_PASSWORD: admin
  # GOOGLE_ANALYTICS_ID: UA-XXXXXX-1
  # ROLLBAR_ACCESS_TOKEN: <token>
  # ROLLBAR_ENV: <env> - Defaults to Rails.env
