development:
  clients:
    default:
      uri: "mongodb://heroku_rk350hdp:k441hshmcb67ama56vcgh0bm58@ds157258.mlab.com:57258/heroku_rk350hdp"
      options:
  options:
test:
  clients:
    default:
      database: feedcast_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
beta:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] %>
production:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] %>
