# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eac100c6e9b7f6b6fe2c2e2a7cf4e53369c6b09f0177a848c0936c14b291487d159acb1873de5cf83c93543016441f1dfa8f0be98eecd8c21aa539be667b67b8

test:
  secret_key_base: c35aa2abc38cd543d31381de99c8f0ce6e3b6c5c1e335f162ed55c8d99bc856b238e9b608e764b2641a9cad9a829e5f672c93b4d9d06a3eff2f58bff27bee1d2

beta:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
