---
:verbose: true
:concurrency: 10
:timeout: 30
:queues:
  - synchronization
  - analysis
  - default
production:
  :concurrency: 15
beta:
  :concurrency: 5
development:
  :concurrency: 5

:schedule:
  channel_synchronization_scheduler_job:
    every: 15m
    class: ChannelSynchronizationSchedulerJob
  audio_synchronization_scheduler_job:
    every: 30m
    class: AudioAnalysisSchedulerJob
