---
:verbose: true
:timeout: 30
:queues:
  - synchronization
  - indexing
  - analysis
  - default
production:
  :concurrency: 15
beta:
  :concurrency: 5
development:
  :concurrency: 5

:schedule:
  channel_synchronization_scheduler_job:
    every: 10m
    class: ChannelSynchronizationSchedulerJob
  audio_synchronization_scheduler_job:
    every: 15m
    class: AudioAnalysisSchedulerJob
  episode_indexer_scheduler_job:
    every: 48h
    class: EpisodeIndexerSchedulerJob
